name: OmegaPlugin
version: '${project.version}'
main: com.notverygoodatthis.omegaplugin.OmegaPlugin
api-version: 1.19
authors: [ NotVeryGoodAtThis ]
description: The Minecraft Spigot server plugin for the Omega SMP

commands:
  omegaset:
    description: Set a player's lives (ADMIN ONLY)
    usage: /<command>
    permission: omegasmp.admin
  deposit:
    description: Deposit some of your lives in an item form
    usage: /<command>
  omegarevive:
    description: Revive a banned player
    usage: /<command>
  omegaitem:
    description: Get an Omega SMP OP item (ADMIN ONLY)
    usage: /<command>
    permission: omegasmp.admin
  afk:
    description: Toggles your AFK status
    usage: /<command>
  spawncheck:
    description: Check if the player is standing in spawn.
    usage: /<command>
  spawnset:
    description: Sets the spawn area counted for the kill ban
    usage: /<command>
